### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by tiramisutes** [yechengxi/Sparc#1]
I have a problem when running Sparc.
```
Sparc b backbone_raw.fasta m backbone.mapped.m5 k 2 g 2 c 2 t 0.1 HQ_Prefix Contig boost 5 o Call-consensus
For help: Sparc -h
Backbone size: 36234
bug
AT
GT
bug
CT
AA
bug
TC
AA
Error.
bug
TT
TC
bug
TG
TT
bug
AT
TT
bug
GT
GA
bug
CC
TT
bug
TC
CT
bug
AC
AG
bug
GA
AA
Error.
Segmentation fault (core dumped)
```

**Comment by yechengxi** [comment]
Are you able to run the test data we provided?
Did you use SparseAssembler to generate your contigs?

**Comment by tiramisutes** [comment]
Yes, I used  SparseAssembler to generate my contigs and used follows command to generate  backbone.mapped.m5 file.
`blasr --nproc 6 PacBio.fasta backbone_raw.fasta --bestn 1 -m 5 --minMatch 19 --out backbone.mapped.m5`

**Comment by yechengxi** [comment]
Did you concatenate the contigs and the Pacbio reads into one file?

**Comment by tiramisutes** [comment]
You mean in blasr the <PacBio.fasta> file should be substitute with <ctg_pb.fasta> ( `cat contigs.txt PacBio.fasta >ctg_pb.fasta`) ?

**Comment by yechengxi** [comment]
yes.
