### ISSUE TITLE
Sparc：未找到命令

### ISSUE THREAD

**Issue by xieruopeng** [yechengxi/Sparc#2]
xrp@xrp-Precision-T1700:~/source$ cd Sparc-master/
xrp@xrp-Precision-T1700:~/source/Sparc-master$ g++ -O3 -o Sparc *.cpp
xrp@xrp-Precision-T1700:~/source/Sparc-master$ Sparc
Sparc：未找到命令
xrp@xrp-Precision-T1700:~/source/Sparc-master$

**Comment by yechengxi** [comment]
Maybe you don't have a compiler here or don't have the code in the right place.

**Comment by xieruopeng** [comment]
./Sparc   is   right. thank you !
