### ISSUE TITLE
data error

### ISSUE THREAD

**Issue by xieruopeng** [yechengxi/Sparc#3]
I use the test data to run out of ConsensusOutput.consensus.fasta  which is completely different from backbone-0.fasta

**Comment by yechengxi** [comment]
Consensus means polished. Backbone means unpolished. They should be different.

**Comment by xieruopeng** [comment]
But they are totally different(differences> 90%). Normally，the backbone should be similar to the consensus（similarity>80%）

**Comment by yechengxi** [comment]
Maybe try the precompiled version to see if it works.
