### ISSUE TITLE
error rates

### ISSUE THREAD

**Issue by xieruopeng** [yechengxi/Sparc#4]
[REF]                [QRY]                           
  [Sequences]                                                                         
  TotalSeqs                          1                    1                           
  AlignedSeqs               1(100.00%)           1(100.00%)                           
  UnalignedSeqs               0(0.00%)             0(0.00%)                           
                                                                                      
  [Bases]                                                                             
  TotalBases                   4641652              4655636
  AlignedBases         4638048(99.92%)      4653585(99.96%)
  UnalignedBases           3604(0.08%)          2051(0.04%)
                                                                                      
  [Alignments]                                                                        
  1-to-1                            28                   28
  TotalLength                  4643106              4653740
  AvgLength                  165825.21            166205.00
  AvgIdentity                    99.57                99.57
  
  M-to-M                            29                   29
  TotalLength                  4643875              4654509
  AvgLength                  160133.62            160500.31
  AvgIdentity                    99.57                99.57
                                                                                      
  [Feature Estimates]                                                                 
  Breakpoints                       56                   56
  Relocations                        2                    1
  Translocations                     0                    0                           
  Inversions                         2                    2                           
                                                                                      
  Insertions                        13                   23
  InsertionSum                    3717                 3585
  InsertionAvg                  285.92               155.87
  
  TandemIns                          1                    3
  TandemInsSum                     113                  319
  TandemInsAvg                  113.00               106.33

This is the result which use the dnadiff function in MUMmer3. Which parameter is the final consensus error rates?

**Comment by yechengxi** [comment]
AvgIdentity in the 1-1 alignment.

**Comment by xieruopeng** [comment]
Could you tell me how to use DBG2OLC to generate the backbone of the testdata ?Thank you very much！

**Comment by yechengxi** [comment]
Some extra data is required. You may go through any examples provided in DBG2OLC.
